### ISSUE TITLE
Create/update/delete Local accounts

### ISSUE THREAD

**Issue by anm-mporter** [anm-mporter/anm_itops_playbooks#10]
Local accounts for 
* IOS
* IOS-XE 
* NX-OS
* ASA

All Priv 15

**Comment by anm-joseanda** [comment]
ASA:

username {username} password {password} privilege 15

IOS, IOS-XE:

username {username} secret {password}

NX-OS:

username  {username} password {password}  role network-admin

**Comment by adamordal** [comment]
Added new playbook with name create_accounts.yml
