### ISSUE TITLE
Support setup of SNMP v3

### ISSUE THREAD

**Issue by anm-mporter** [anm-mporter/anm_itops_playbooks#14]
**Devices**
* ios/iosxe
* nx-os

**steps:**
* Create snmp-view
  * Full view: `snmp-server view fullview iso included`
  * Noview: `snmp-server view noview iso excluded`
* Create snmp group `readonly`
  * `snmp-server group readonly v3 priv read fullview write noview`
* create snmp-v3 
   * `snmp-server user USERNAME readonly v3 auth sha BlahBlahBlahpriv aes 128 BlahBlahBlah`

**Comment by adamordal** [comment]
New configure_snmpv3.yml playbook to support this functionality in IOS and NXOS
