### ISSUE TITLE
Add syslog server

### ISSUE THREAD

**Issue by anm-mporter** [anm-mporter/anm_itops_playbooks#3]
add/update syslog server for switches

**Catalyst**
```
service timestamps debug datetime msec localtime show-timezone year
service timestamps log datetime msec localtime show-timezone year
service sequence-numbers
logging trap informational
logging origin-id hostname
logging host SPLUNK_SYSLOG_IP transport udp port SPLUNK_SYSLOG_PORT
```

**NX-OS (does not support custom port)**
```
logging logfile messages 6
logging server YOUR_SYSLOG_SERVER_IP 6 use-vrf YOUR_MGMT_VRF
logging timestamp milliseconds
logging origin-id hostname
logging monitor 6
no logging rate-limit
```

This playbook should support adding the collector IP by default, ands optionally providing a target IP

This playbook should support a default port of 514 and an option target port

This playbook should support adding and removing syslog servers

**Comment by adamordal** [comment]
Added new playbook to allow for NXOS & IOS syslog
